[workspace]
members = [
    "node",
    "runtime",
    "pallets/primitives",
    "pallets/creation",
    "pallets/interaction",
    "pallets/curated-group",
    "pallets/tcx"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
